export const roomCategoryData = [
    { "name" : "Air Terminals" },
{ "name" : "Analytical Beams" },
{ "name" : "Analytical Braces" },
{ "name" : "Analytical Columns" },
{ "name" : "Analytical Floors" },
{ "name" : "Analytical Foundation Slabs" },
{ "name" : "Analytical Isolated Foundations" },
{ "name" : "Analytical Links" },
{ "name" : "Analytical Nodes" },
{ "name" : "Analytical Spaces" },
{ "name" : "Analytical Surfaces" },
{ "name" : "Analytical Wall Foundation" },
{ "name" : "Analytical Walls" },
{ "name" : "Areas" },
{ "name" : "Assemblies" },
{ "name" : "Cable Tray Fittings" },
{ "name" : "Cable Tray Runs" },
{ "name" : "Cable Trays" },
{ "name" : "Casework" },
{ "name" : "Ceilings" },
{ "name" : "Columns" },
{ "name" : "Communication Devices" },
{ "name" : "Conduit Fittings" },
{ "name" : "Conduit Runs" },
{ "name" : "Conduits" },
{ "name" : "Curtain Panels" },
{ "name" : "Curtain Systems" },
{ "name" : "Curtain Wall Mullions" },
{ "name" : "Data Devices" },
{ "name" : "Detail Items" },
{ "name" : "Doors" },
{ "name" : "Duct Accessories" },
{ "name" : "Duct Fittings" },
{ "name" : "Duct Insulations" },
{ "name" : "Duct Linings" },
{ "name" : "Duct Placeholders" },
{ "name" : "Duct Systems" },
{ "name" : "Ducts" },
{ "name" : "Electrical Circuits" },
{ "name" : "Electrical Equipment" },
{ "name" : "Electrical Fixtures" },
{ "name" : "Fire Alarm Devices" },
{ "name" : "Flex Ducts" },
{ "name" : "Flex Pipes" },
{ "name" : "Floors" },
{ "name" : "Slab Edges" },
{ "name" : "Furniture" },
{ "name" : "Furniture Systems" },
{ "name" : "Generic Models" },
{ "name" : "Grids" },
{ "name" : "HVAC Zones" },
{ "name" : "Levels" },
{ "name" : "Lighting Devices" },
{ "name" : "Lighting Fixtures" },
{ "name" : "Mass" },
{ "name" : "Mass Exterior Wall" },
{ "name" : "Mass Floor" },
{ "name" : "Mass Glazing" },
{ "name" : "Mass Interior Wall" },
{ "name" : "Mass Opening" },
{ "name" : "Mass Roof" },
{ "name" : "Mass Skylight" },
{ "name" : "Mass Zone" },
{ "name" : "Materials" },
{ "name" : "Mechanical Equipment" },
{ "name" : "Nurse Call Devices" },
{ "name" : "Parking" },
{ "name" : "Parts" },
{ "name" : "Pipe Accessories" },
{ "name" : "Pipe Fittings" },
{ "name" : "Pipe Insulations" },
{ "name" : "Pipe Placeholders" },
{ "name" : "Pipes" },
{ "name" : "Piping System" },
{ "name" : "Planting" },
{ "name" : "Plumbing Fixtures" },
{ "name" : "Project Information" },
{ "name" : "Railings" },
{ "name" : "Handrails" },
{ "name" : "Supports" },
{ "name" : "Terminators" },
{ "name" : "Top Rails" },
{ "name" : "Ramps" },
{ "name" : "Rebar Shape" },
{ "name" : "Roads" },
{ "name" : "Roofs" },
{ "name" : "Fascias" },
{ "name" : "Gutters" },
{ "name" : "Rooms" },
{ "name" : "Security Devices" },
{ "name" : "Shaft Openings" },
{ "name" : "Sheets" },
{ "name" : "Site" },
{ "name" : "Property Line Segments" },
{ "name" : "Property Lines" },
{ "name" : "Pads" },
{ "name" : "Spaces" },
{ "name" : "Specialty Equipment" },
{ "name" : "Sprinklers" },
{ "name" : "Stairs" },
{ "name" : "Landings" },
{ "name" : "Runs" },
{ "name" : "Supports" },
{ "name" : "Structural Area Reinforcement" },
{ "name" : "Structural Beam Systems" },
{ "name" : "Structural Columns" },
{ "name" : "Structural Connections" },
{ "name" : "Structural Fabric Areas" },
{ "name" : "Structural Fabric Reinforcement" },
{ "name" : "Structural Foundations" },
{ "name" : "Structural Framing" },
{ "name" : "Structural Internal Loads" },
{ "name" : "Internal Area Loads" },
{ "name" : "Internal Line Loads" },
{ "name" : "Internal Point Loads" },
{ "name" : "Structural Loads" },
{ "name" : "Area Loads" },
{ "name" : "Line Loads" },
{ "name" : "Point Loads" },
{ "name" : "Structural Path Reinforcement" },
{ "name" : "Structural Rebar" },
{ "name" : "Structural Stiffeners" },
{ "name" : "Structural Trusses" },
{ "name" : "Switch System" },
{ "name" : "Telephone Devices" },
{ "name" : "Topography" },
{ "name" : "Views" },
{ "name" : "Walls" },
{ "name" : "Wall Sweeps" },
{ "name" : "Windows" },
{ "name" : "Wires" }
];