"use strict";
exports.roomInstancesData = [
    {
        "Area": "424,53",
        "CQ_InstanceGUID": "7c1b9809-a6ca-498d-90ac-ad229240f08c",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "22, 24",
        "Materiallista Typ": "Golv",
        "Kort Beskrivning Material": "Plastmatta blå",
        "Golv": "22, 24",
        "Lång Beskrivning Material": "Plastmatta blå, PVC-fri",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Inredning": "",
        "Övrigt": "",
        "Kommentar": "",
        "Anmärkning Instans": "",
        "Design Option": "",
        "Fas": "",
        "Funktion": "",
        "Revit_GUID": "",
        "Revit_ID": "",
        "Rivning": "",
        "Stomkomplettering": "",
        "Bilagor från Revit Callout": "Välj",
        "Kort Beskrivning Kulör": "NCS S 0502-Y",
        "Kulörlista": {
            "546eebc04ba222d61763db5e": "54c95aeb4ba222bc2c636952"
        },
        "Målninglista": {
            "546eebc04ba222d61763db5e": "Värde saknas"
        },
        "AMA-kod": "43.E",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Planvy Bild": "TestImage12.jpg",
        "Ingår i rapport": "Ja",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "TEXT parameter": "",
        "Test text": "",
        "CQInstanceGUID": "",
        "Bilaga rum": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Rumsnummerrr": "A001",
        "Rumsnamn": "FOAJÉ/NEDRE LOUNG"
    },
    {
        "Area": "15,25",
        "CQ_InstanceGUID": "193a61ad-4614-411b-a6e8-fb9646b1ff8e",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Planvy Bild": "TestImage12.jpg",
        "Ingår i rapport": "Ja",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "TEXT parameter": "",
        "Test text": "",
        "Anmärkning Instans": "",
        "Kommentar": "",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "CQInstanceGUID": "",
        "Design Option": "",
        "Bilaga rum": "",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Materiallista Typ": "",
        "Golv": "",
        "Vägg": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Material": "",
        "Inredning": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "A002",
        "Rumsnamn": "PENTRY"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,66",
        "CQ_InstanceGUID": "05686dfe-08b2-4cea-b2ea-0b3b130a3a5c",
        "Design Option": "",
        "Ingår i rapport": "Ja",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 00",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Golv": "",
        "Inredning": "",
        "Kommentar": "",
        "Fas": "",
        "Funktion": "",
        "Revit_GUID": "",
        "Revit_ID": "",
        "Bilagor från Revit Callout": "Välj",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Planvy Bild": "TestImage12.jpg",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "TEXT parameter": "",
        "Test text": "",
        "CQInstanceGUID": "",
        "Bilaga rum": "",
        "Kommentar Kulör": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Rumsnummerrr": "A003",
        "Rumsnamn": "WC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,63",
        "CQ_InstanceGUID": "464be053-da8a-40a3-a683-20952c189bdd",
        "Design Option": "",
        "Golv": "",
        "Ingår i rapport": "",
        "Inredning": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 00",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Planvy Bild": "testimage001.jpg",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "Kort Beskrivning Kulör": "",
        "TEXT parameter": "",
        "Test text": "",
        "Kommentar": "",
        "CQInstanceGUID": "",
        "Bilaga rum": "Välj",
        "Kommentar Kulör": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Rumsnummerrr": "A004",
        "Rumsnamn": "WC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,72",
        "CQ_InstanceGUID": "1fd6d91d-b6b2-4437-abd9-d3751dd6b38c",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 00",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Golv": "",
        "Kommentar Kulör": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Inredning": "",
        "Rumsnummerrr": "A005",
        "Rumsnamn": "WC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,72",
        "CQ_InstanceGUID": "ddb9ccd7-ae2d-49fe-b95f-92b4502a9083",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 00",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Golv": "",
        "Kommentar Kulör": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Inredning": "",
        "Rumsnummerrr": "A006",
        "Rumsnamn": "WC"
    },
    {
        "Area": "5,05",
        "CQ_InstanceGUID": "f18586c0-729f-4815-839f-3b002e969930",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Planvy Bild": "testimage001.jpg",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "A007",
        "Rumsnamn": "FRD"
    },
    {
        "Area": "217,6",
        "CQ_InstanceGUID": "fe7d7352-4622-40b2-ae8d-94a9bc720195",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Planvy Bild": "TestImage12.jpg",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "Kort Beskrivning Kulör": "",
        "TEXT parameter": "",
        "Test text": "",
        "Anmärkning Instans": "",
        "Golv": "",
        "Kommentar": "",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "CQInstanceGUID": "",
        "Design Option": "",
        "Bilaga rum": "Välj",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Materiallista Typ": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Material": "",
        "Inredning": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "B008",
        "Rumsnamn": "FOAJE"
    },
    {
        "Area": "8,15",
        "CQ_InstanceGUID": "7ef2a7af-e4c5-4f08-a240-eeb7a7c91f51",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "B009",
        "Rumsnamn": "KONTOR"
    },
    {
        "Area": "7,96",
        "CQ_InstanceGUID": "7c985937-b395-4bf3-bbc4-e06b7aafd121",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "B010",
        "Rumsnamn": "KONTOR"
    },
    {
        "Area": "8,48",
        "CQ_InstanceGUID": "a3937dc0-ebfc-4df1-b825-c496c62923df",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "B011",
        "Rumsnamn": "KONTOR"
    },
    {
        "Area": "23,99",
        "CQ_InstanceGUID": "1751db12-01ef-43eb-8c41-b67ddf9beda0",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "B012",
        "Rumsnamn": "KORRIDOR"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,32",
        "CQ_InstanceGUID": "0e726e8a-7889-41ee-b806-35e0ca967fb9",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 01",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Golv": "",
        "Kommentar Kulör": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Inredning": "",
        "Rumsnummerrr": "B013",
        "Rumsnamn": "WC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,2",
        "CQ_InstanceGUID": "806cba8b-16db-4c08-a292-287ee2bf779c",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 01",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Golv": "",
        "Kommentar Kulör": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Inredning": "",
        "Rumsnummerrr": "B014",
        "Rumsnamn": "WC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "6,11",
        "CQ_InstanceGUID": "cddeabc7-30e1-49c9-a3b1-10320837b68a",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 01",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kommentar Kulör": "",
        "Inredning": "",
        "Golv": "",
        "Rumsnummerrr": "B015",
        "Rumsnamn": "HWC"
    },
    {
        "Area": "5,53",
        "CQ_InstanceGUID": "eb161cda-dba6-438f-ba95-2e6e7a612321",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kulör och glans": "testtet",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "56-03510",
        "Kort Beskrivning Målning": "Målning gips",
        "Lång Beskrivning Målning": "",
        "Kod Material": "123456789, 0101",
        "Vägg": "123456789",
        "Materiallista Typ": "Vägg, Golv",
        "Inredning": "",
        "Golv": "0101",
        "Sockel": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "HARIS": "",
        "LiO Byggnad": "",
        "Anmärkning Instans": "",
        "Kommentar": "",
        "Design Option": "",
        "Bilagor från Revit Callout": "",
        "Kulörlista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab135173bd54c6298b7cc3"
        },
        "Målninglista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab13be73bd54f07e8b96ce"
        },
        "AMA-kod": "44.B",
        "Kort Beskrivning Material": "Forbo marmoleum",
        "Rumsnummerrr": "B016",
        "Rumsnamn": "FÖRRUM"
    },
    {
        "Area": "48,12",
        "CQ_InstanceGUID": "47b0450a-a450-4ba3-b692-224c7dd0fa86",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kulör och glans": "testtet",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "56-03510",
        "Kort Beskrivning Målning": "Målning gips",
        "Lång Beskrivning Målning": "",
        "Kod Material": "123456789, 0101",
        "Vägg": "123456789",
        "Materiallista Typ": "Vägg, Golv",
        "Inredning": "",
        "Golv": "0101",
        "Sockel": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "HARIS": "",
        "LiO Byggnad": "",
        "Anmärkning Instans": "",
        "Kommentar": "",
        "Design Option": "",
        "Bilagor från Revit Callout": "",
        "Kulörlista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab135173bd54c6298b7cc3"
        },
        "Målninglista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab13be73bd54f07e8b96ce"
        },
        "AMA-kod": "44.B",
        "Kort Beskrivning Material": "Forbo marmoleum",
        "Rumsnummerrr": "B017",
        "Rumsnamn": "PERSONALRUM"
    },
    {
        "Area": "57,65",
        "CQ_InstanceGUID": "cf188fca-370c-4425-9a73-718658d390a6",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kulör och glans": "testtet",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "56-03510",
        "Kort Beskrivning Målning": "Målning gips",
        "Lång Beskrivning Målning": "",
        "Kod Material": "123456789, 0101",
        "Vägg": "123456789",
        "Materiallista Typ": "Vägg, Golv",
        "Inredning": "",
        "Golv": "0101",
        "Sockel": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "HARIS": "",
        "LiO Byggnad": "",
        "Anmärkning Instans": "",
        "Kommentar": "",
        "Design Option": "",
        "Bilagor från Revit Callout": "",
        "Kulörlista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab135173bd54c6298b7cc3"
        },
        "Målninglista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab13be73bd54f07e8b96ce"
        },
        "AMA-kod": "44.B",
        "Kort Beskrivning Material": "Forbo marmoleum",
        "Rumsnummerrr": "B018",
        "Rumsnamn": "KONFERENSRUM"
    },
    {
        "Area": "338,46",
        "CQ_InstanceGUID": "6bae290d-390f-46eb-b014-c2f9993b0698",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "B019",
        "Rumsnamn": "ADMIN"
    },
    {
        "Area": "258,45",
        "CQ_InstanceGUID": "9280b4eb-cb50-4654-afb7-60784861066f",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "Materiallista Typ": "",
        "Kort Beskrivning Material": "",
        "Golv": "",
        "Lång Beskrivning Material": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Inredning": "",
        "Övrigt": "",
        "Kommentar": "",
        "Anmärkning Instans": "",
        "Design Option": "",
        "Fas": "",
        "Funktion": "",
        "Revit_GUID": "",
        "Revit_ID": "",
        "Rivning": "",
        "Stomkomplettering": "",
        "Bilagor från Revit Callout": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "Kort Beskrivning Kulör": "",
        "LiO Byggnad": "",
        "TEXT parameter": "",
        "Test text": "",
        "Bilaga rum": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Rumsnummerrr": "A020",
        "Rumsnamn": "VERKSTADSLOKAL"
    },
    {
        "Area": "16,45",
        "CQ_InstanceGUID": "2030ff3c-cace-4023-8570-6e245853e46a",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "B021",
        "Rumsnamn": "VIDEOKONFERENS"
    },
    {
        "Area": "30,32",
        "CQ_InstanceGUID": "7e0e2113-7bb3-4543-9b89-f6b4860949a3",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "A022",
        "Rumsnamn": "VIND/LJUS LABB"
    },
    {
        "Area": "11,37",
        "CQ_InstanceGUID": "0ac26029-df01-4fb4-bacd-450cf308c0a8",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "B023",
        "Rumsnamn": "VINDFÅNG"
    },
    {
        "Area": "14,49",
        "CQ_InstanceGUID": "af19e11d-950e-4d82-8e7b-ab6b9e3f62c5",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Planvy Bild": "TestImage12.jpg",
        "Ingår i rapport": "Ja",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "Kort Beskrivning Kulör": "",
        "TEXT parameter": "",
        "Test text": "",
        "Anmärkning Instans": "",
        "Golv": "",
        "Kommentar": "",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "CQInstanceGUID": "",
        "Design Option": "",
        "Bilaga rum": "",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Materiallista Typ": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Material": "",
        "Inredning": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "A024",
        "Rumsnamn": "FRD"
    },
    {
        "Area": "6,82",
        "CQ_InstanceGUID": "94586f0b-0b06-407c-b627-3b887ae510e2",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Planvy Bild": "TestImage12.jpg",
        "Ingår i rapport": "Ja",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "Kort Beskrivning Kulör": "",
        "TEXT parameter": "",
        "Test text": "",
        "Anmärkning Instans": "",
        "Golv": "",
        "Kommentar": "",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "CQInstanceGUID": "",
        "Design Option": "",
        "Bilaga rum": "",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Materiallista Typ": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Material": "",
        "Inredning": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "A025",
        "Rumsnamn": "SPÅNSUG"
    },
    {
        "Area": "8,86",
        "CQ_InstanceGUID": "9435aee2-2b1a-4c73-98a7-3f3d13e869db",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kulör och glans": "testtet",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "56-03510",
        "Kort Beskrivning Målning": "Målning gips",
        "Lång Beskrivning Målning": "",
        "Kod Material": "123456789, 0101",
        "Vägg": "123456789",
        "Materiallista Typ": "Vägg, Golv",
        "Inredning": "",
        "Golv": "0101",
        "Sockel": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "HARIS": "",
        "LiO Byggnad": "",
        "Anmärkning Instans": "",
        "Kommentar": "",
        "Design Option": "",
        "Bilagor från Revit Callout": "",
        "Kulörlista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab135173bd54c6298b7cc3"
        },
        "Målninglista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab13be73bd54f07e8b96ce"
        },
        "AMA-kod": "44.B",
        "Kort Beskrivning Material": "Forbo marmoleum",
        "Rumsnummerrr": "A026",
        "Rumsnamn": "KOMPR. RUM"
    },
    {
        "Area": "116,51",
        "CQ_InstanceGUID": "3c08b22c-f4da-4ffa-99b3-15b20f25ccd9",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "A027",
        "Rumsnamn": "FÖRELÄSNINGSSAL"
    },
    {
        "Area": "18,29",
        "CQ_InstanceGUID": "7da7f6ef-ebb4-4f86-b5a0-5c1b227927ce",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kulör och glans": "testtet",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "56-03510",
        "Kort Beskrivning Målning": "Målning gips",
        "Lång Beskrivning Målning": "",
        "Kod Material": "123456789, 0101",
        "Vägg": "123456789",
        "Materiallista Typ": "Vägg, Golv",
        "Inredning": "",
        "Golv": "0101",
        "Sockel": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "HARIS": "",
        "LiO Byggnad": "",
        "Anmärkning Instans": "",
        "Kommentar": "",
        "Design Option": "",
        "Bilagor från Revit Callout": "",
        "Kulörlista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab135173bd54c6298b7cc3"
        },
        "Målninglista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab13be73bd54f07e8b96ce"
        },
        "AMA-kod": "44.B",
        "Kort Beskrivning Material": "Forbo marmoleum",
        "Rumsnummerrr": "A028",
        "Rumsnamn": "ELRUM"
    },
    {
        "Area": "66,78",
        "CQ_InstanceGUID": "b6876697-820c-438e-8a03-f46c97992361",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Planvy Bild": "TestImage12.jpg",
        "Ingår i rapport": "Ja",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "Kort Beskrivning Kulör": "",
        "TEXT parameter": "",
        "Test text": "",
        "Anmärkning Instans": "",
        "Golv": "",
        "Kommentar": "",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "CQInstanceGUID": "",
        "Design Option": "",
        "Bilaga rum": "",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Materiallista Typ": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Material": "",
        "Inredning": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "A029",
        "Rumsnamn": "FRD"
    },
    {
        "Area": "3,32",
        "CQ_InstanceGUID": "6060fef3-7959-488d-860e-49f0f660c957",
        "Plan": "Plan 01",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "Test01, 24",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "Inredning, Golv",
        "Inredning": "Test01",
        "Golv": "24",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "testtet",
        "Glans": "Glans 40",
        "Kulör kod": "NCS S 0500 N",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "26-01810",
        "Kort Beskrivning Målning": "Betong",
        "Lång Beskrivning Målning": "",
        "Kulörlista": {
            "56aa7fb873bd54c6298b7b0f": "56ab135173bd54c6298b7cc3",
            "56683491f86c228a138b45f2": "Värde saknas"
        },
        "Målninglista": {
            "56aa7fb873bd54c6298b7b0f": "54c75a4b4ba2224b2463699b",
            "56683491f86c228a138b45f2": "Värde saknas"
        },
        "Rumsnummerrr": "B030",
        "Rumsnamn": "STÄD",
        "Kort Beskrivning Kulör": "",
        "Test": "",
        "URL": "",
        "Avdelning": "",
        "A kommentar": "",
        "RFP Nummer": "",
        "Ingår i rapport": "",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "LiO Byggnad": "",
        "TEXT parameter": "",
        "Test text": "",
        "rrrrrrrrrrrrrrrrrrrrrrrrrrrrr": "",
        "Anmärkning Instans": "",
        "Kommentar": "",
        "CQInstanceGUID": "",
        "Design Option": "",
        "Bilaga rum": "dummy.pdf",
        "Bilagor från Revit Callout": "Välj",
        "instance_Bilaga_rum": "56433ee673bd5446548b4aaa"
    },
    {
        "Area": "6,64",
        "CQ_InstanceGUID": "dcd3db78-3f26-43e7-a8f8-d95916953d72",
        "Plan": "Plan 00",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "A031",
        "Rumsnamn": "KONTOR"
    },
    {
        "Area": "1015,05",
        "CQ_InstanceGUID": "039751a9-2bb9-440a-9082-b6f503aa5147",
        "Plan": "Plan 02",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "C032",
        "Rumsnamn": "ELEVOMRÅDE"
    },
    {
        "Area": "102,92",
        "CQ_InstanceGUID": "8f49c498-3e8f-4c85-adfe-cc0c80905efe",
        "Plan": "Plan 03",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "D001",
        "Rumsnamn": "DATORSAL"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "6,11",
        "CQ_InstanceGUID": "2b822040-e678-4c32-bac3-a74d4b2cfc23",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 03",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kommentar Kulör": "",
        "Inredning": "",
        "Golv": "",
        "Rumsnummerrr": "D011",
        "Rumsnamn": "HWC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,32",
        "CQ_InstanceGUID": "aefda97a-da54-4e26-85b2-b6b3da3356e3",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "Test02, 30, Hare, Test 05, Test 04, My new for test, 28, Test, 22, New again, 25, 0101, Sanel",
        "Kort Beskrivning Material": "Målning gips, Klinker, Forbo marmoleum",
        "Kulörlista": {
            "546eebc04ba222d61763db5e": "Värde saknas",
            "566e9f9373bd54eb068b6183": "Värde saknas",
            "56683565f86c2289138b461a": "Värde saknas",
            "566ee61773bd54eb068b65dc": "Värde saknas",
            "566ee47773bd54eb068b657a": "Värde saknas",
            "566ee0b373bd54732d8b4639": "Värde saknas",
            "566fd3fd73bd5445038b667c": "Värde saknas",
            "56683527f86c223b148ba8c5": "Värde saknas",
            "566ee08473bd5445038b60bd": "Värde saknas",
            "566ff083f86c2266178b4661": "Värde saknas",
            "566fd47a73bd5445038b670e": "Värde saknas",
            "566834f8f86c228a138b4611": "Värde saknas",
            "566ff0bff86c2267178b46e6": "Värde saknas",
            "56325cdef86c2280348b4579": "Värde saknas",
            "566ee5a373bd54732d8b469d": "Värde saknas"
        },
        "Lång Beskrivning Material": "Plastmatta blå, PVC-fri",
        "Målninglista": {
            "546eebc04ba222d61763db5e": "Värde saknas",
            "566e9f9373bd54eb068b6183": "Värde saknas",
            "56683565f86c2289138b461a": "Värde saknas",
            "566ee61773bd54eb068b65dc": "Värde saknas",
            "566ee47773bd54eb068b657a": "Värde saknas",
            "566ee0b373bd54732d8b4639": "Värde saknas",
            "566fd3fd73bd5445038b667c": "Värde saknas",
            "56683527f86c223b148ba8c5": "Värde saknas",
            "566ee08473bd5445038b60bd": "Värde saknas",
            "566ff083f86c2266178b4661": "Värde saknas",
            "566fd47a73bd5445038b670e": "Värde saknas",
            "566834f8f86c228a138b4611": "Värde saknas",
            "566ff0bff86c2267178b46e6": "Värde saknas",
            "56325cdef86c2280348b4579": "Värde saknas",
            "566ee5a373bd54732d8b469d": "Värde saknas"
        },
        "Materiallista Typ": "Golv",
        "Plan": "Plan 03",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "44.B, KBC.321",
        "Golv": "Test02, 30, Hare, Test 05, Test 04, My new for test, 28, Test, 22, New again, 25, 0101, Sanel",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Kulör": "",
        "TEXT parameter": "",
        "Kommentar": "",
        "CQInstanceGUID": "",
        "Bilaga rum": "Välj",
        "COM_ROOM_COLORLISTA": {
            "566e9f9373bd54eb068b6183": "No value",
            "56683565f86c2289138b461a": "No value",
            "566ee5a373bd54732d8b469d": "No value"
        },
        "COM_ROOM_PAINTINGLISTA": {
            "566e9f9373bd54eb068b6183": "No value",
            "56683565f86c2289138b461a": "No value",
            "566ee5a373bd54732d8b469d": "No value"
        },
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Planvy Bild": "testimage001.jpg",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "LiO Byggnad": "",
        "Test text": "",
        "Bilagor från Revit Callout": "Välj",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Inredning": "",
        "Rumsnummerrr": "D012",
        "Rumsnamn": "WC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,19",
        "CQ_InstanceGUID": "c050ccc8-25e2-49d6-bb42-17aed877f2dc",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 03",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Golv": "",
        "HARIS": "",
        "Hankesuunnitelmassa kerätty tieto": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Kulör": "",
        "TEXT parameter": "",
        "Kommentar": "",
        "CQInstanceGUID": "",
        "Bilaga rum": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Room Card": [],
        "Planvy Bild": "images1.jpg",
        "Fabrikat": "",
        "Fabrikat kulör": "",
        "Test text": "",
        "LiO Byggnad": "",
        "Bilagor från Revit Callout": "",
        "Inredning": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Rumsnummerrr": "D013",
        "Rumsnamn": "WC"
    },
    {
        "Area": "5,67",
        "CQ_InstanceGUID": "704340c9-570b-463e-9b89-d81c35b2c22e",
        "Plan": "Plan 03",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kulör och glans": "testtet",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "56-03510",
        "Kort Beskrivning Målning": "Målning gips",
        "Lång Beskrivning Målning": "",
        "Kod Material": "123456789, 0101",
        "Vägg": "123456789",
        "Materiallista Typ": "Vägg, Golv",
        "Inredning": "",
        "Golv": "0101",
        "Sockel": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "HARIS": "",
        "LiO Byggnad": "",
        "Anmärkning Instans": "",
        "Kommentar": "",
        "Design Option": "",
        "Bilagor från Revit Callout": "",
        "Kulörlista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab135173bd54c6298b7cc3"
        },
        "Målninglista": {
            "56a9ef7b73bd54f07e8b91a4": "56ab13be73bd54f07e8b96ce"
        },
        "AMA-kod": "44.B",
        "Kort Beskrivning Material": "Forbo marmoleum",
        "Rumsnummerrr": "D014",
        "Rumsnamn": "FÖRRUM"
    },
    {
        "Area": "779,32",
        "CQ_InstanceGUID": "c982f843-f25a-4d71-81fb-9566098d591c",
        "Plan": "Plan 03",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "D015",
        "Rumsnamn": "ELEVOMRÅDE"
    },
    {
        "Area": "60,46",
        "CQ_InstanceGUID": "cdcb7fc7-645c-49eb-ac40-0c326e50c8f5",
        "Plan": "Plan 03",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "Kod Material": "",
        "AMA-kod": "",
        "Kommentar Kulör": "",
        "Kort Beskrivning Material": "",
        "Lång Beskrivning Material": "",
        "Materiallista Typ": "",
        "Inredning": "",
        "Golv": "",
        "Sockel": "",
        "Vägg": "",
        "Tak": "",
        "Stomkomplettering": "",
        "Rivning": "",
        "Övrigt": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kulörlista": [],
        "Målninglista": [],
        "Rumsnummerrr": "D016",
        "Rumsnamn": "FÖRELÄSNINGSSAL"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "6,11",
        "CQ_InstanceGUID": "1a61db46-5742-419e-89ab-c8e5db2b4d93",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 02",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Lång Beskrivning Kulör": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Lång Beskrivning Målning": "",
        "Kommentar Kulör": "",
        "Inredning": "",
        "Golv": "",
        "Rumsnummerrr": "C017",
        "Rumsnamn": "HWC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,19",
        "CQ_InstanceGUID": "5b07f65c-cd1c-49d2-b28e-079f5a3aee45",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 02",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Golv": "",
        "Kommentar Kulör": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Inredning": "",
        "Rumsnummerrr": "C018",
        "Rumsnamn": "WC"
    },
    {
        "Övrigt": "",
        "Anmärkning Instans": "",
        "Area": "2,32",
        "CQ_InstanceGUID": "86b7229c-a2d4-4b8c-9b71-b8d364d39a3e",
        "Design Option": "",
        "Ingår i rapport": "",
        "Kod Material": "",
        "Kort Beskrivning Material": "",
        "Kulörlista": [],
        "Lång Beskrivning Material": "",
        "Målninglista": [],
        "Materiallista Typ": "",
        "Plan": "Plan 02",
        "Rivning": "",
        "Sockel": "",
        "Stomkomplettering": "",
        "Tak": "",
        "Vägg": "",
        "category_id": [
            {
                "id": "-2000160",
                "name": "Rooms"
            }
        ],
        "create_date": "2015-01-12 14:18:42",
        "model_id": "ume-ah-skola",
        "AMA-kod": "",
        "Kulör och glans": "",
        "Glans": "",
        "Kulör kod": "",
        "Målnings Kod": "",
        "Kort Beskrivning Målning": "",
        "Golv": "",
        "Kommentar Kulör": "",
        "Lång Beskrivning Kulör": "",
        "Lång Beskrivning Målning": "",
        "Inredning": "",
        "Rumsnummerrr": "C019",
        "Rumsnamn": "WC"
    }
];
//# sourceMappingURL=roomInstancesData.js.map